name: Update Quote

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 12:00 PM IST (06:30 UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update Quote
        run: node update-quote.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git add README.md
          git -c user.name='Sudharsana125' -c user.email='[YOUR_EMAIL@example.com]' commit -m "Update README with daily quote" -a
          git push
